linters:
  eslint:
    config: './.eslintrc.json'
  rubocop:
    display_cop_names: true
    config: './rubocop.yml'
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "vendor/cache/**/*"
    - "node_modules/**/*"
